# Generated by Django 5.0.6 on 2024-07-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateSubsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, unique=True)),
                ('subsidy_rate', models.FloatField(help_text='Subsidy rate as a percentage')),
                ('state_generation', models.FloatField(default=None, help_text='Generation rate per state', null=True)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='statecity.city')),
            ],
        ),
    ]
