# Generated by Django 5.0.6 on 2024-07-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statecity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_average_consumption', models.IntegerField(default=None, help_text='Monthly average electricity consumption (units)', null=True)),
                ('load_requirement', models.FloatField(default=0.0, help_text='Load requirement (kW)')),
                ('roof_area', models.FloatField(default=0.0, help_text='Roof area in square feet')),
                ('state_generation', models.FloatField(default=None, help_text='Generation rate per state', null=True)),
                ('average_rate_per_unit', models.FloatField(default=None, help_text='Average rate of electricity per unit/kWh', null=True)),
                ('margin_money_percentage', models.FloatField(default=20.0, help_text='Margin Money (Minimum 20%)', null=True)),
                ('interest_rate', models.FloatField(default=8.9, help_text='Rate of interest (%)', null=True)),
                ('loan_period', models.IntegerField(default=10, help_text='Loan period in years', null=True)),
                ('city', models.ForeignKey(help_text='Select the city', null=True, on_delete=django.db.models.deletion.SET_NULL, to='statecity.city')),
                ('state', models.ForeignKey(help_text='Select the state', null=True, on_delete=django.db.models.deletion.SET_NULL, to='statecity.statesubsidy')),
            ],
        ),
    ]
